src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity("username")
 */
class User implements UserInterface, \Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isActivated;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getIsActivated(): ?bool
    {
        return $this->isActivated;
    }

    public function setIsActivated(bool $isActivated): self
    {
        $this->isActivated = $isActivated;

        return $this;
    }

    public function __construct()
    {
        $this->isActivated = true;
    }

    public function getSalt()
    {
        return null;
    }

    public function getRoles()
    {
        if ($this->username === 'admin') {
            return ['ROLE_ADMIN'];
        } else {
            return ['ROLE_USER'];
        }
    }

    public function eraseCredentials()
    {

    }

    public function serialize()
    {
        return serialize([
           $this->id,
           $this->username,
           $this->password,
           $this->isActivated
        ]);
    }

    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->username,
            $this->password,
            $this->isActivated,
            ) = $this->unserialize($serialized, ['arrowed_classes' => false]);
    }
}

src/Form/HelloType.php
<?php
namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

class HelloType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $option)
    {
        $builder
            ->add('name', TextType::class)
            ->add('mail' , EmailType::class)
            ->add('save', SubmitType::class, ['label' => 'Click']);
    }
}

src/Controller/HelloController.php
<?php

namespace App\Controller;

use App\Entity\Person;
use App\Form\HelloType;
use App\Form\PersonType;
use Doctrine\ORM\Query\ResultSetMappingBuilder;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Filesystem\Exception\IOExceptionInterface;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Finder\Finder;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use Symfony\Component\Validator\Constraints as Assert;

class HelloController extends AbstractController
{
    /**
     * @Route("/index", name="index")
     */
    public function index(Request $request)
    {
        $data = [
            ['name' => 'Taro', 'age' => 37, 'mail' => 'taro@yamada'],
            ['name' => 'Hanako', 'age' => 29, 'mail' => 'hanako@flower'],
            ['name' => 'Sachiko', 'age' => 43, 'mail' => 'sachico@happy'],
            ['name' => 'Jiro', 'age' => 18, 'mail' => 'jiro@change'],
        ];
        return $this->render('hello/login.html.twig', [
            'title' => 'Hello',
            'data' => $data,
            'leader' => '<h1>見出し</h1>',
            'upper' => 'Upp,er',
            'minus' => -1000,
            'now' => date('Y-m-d'),
            'arr' => ['apple'],
            'num' => 1.32323,
            'nums' => [1,4,2,4,6,7,8,9],
            'url' => 'http://127.0.0.1:8001/hello'
        ]);
    }


    /**
     * @Route("/hello", name="hello")
     * @param Request $request
     * @param SessionInterface $session
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function hello(Request $request)
    {
        if (!$this->getUser()->getIsActivated()) {
            throw new AccessDeniedException('Unable to access!');
        }

        return $this->render('hello/index.html.twig', [
            'title' => 'Hello',
            'message' => 'User Information.',
            'user' => $this->getUser(),
        ]);
    }

    /**
     * @Route("/clear", name="class")
     */
    public function clear(Request $request, SessionInterface $session)
    {
        $session->getFlashBag()->clear();
        return $this->redirect('/hello');
    }


    /**
     * @Route("/find", name="find")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function find(Request $request)
    {
        $formObj = new FindForm();
        $form = $this->createFormBuilder($formObj)
            ->add('find', TextType::class)
            ->add('save', SubmitType::class, ['label' => 'Click'])
            ->getForm();

        $repository = $this->getDoctrine()->getRepository(Person::class);

        $manager = $this->getDoctrine()->getManager();

        $mapping = new ResultSetMappingBuilder($manager);
        $mapping->addRootEntityFromClassMetadata('App\Entity\Person', 'p');

        if ($request->getMethod() == 'POST') {
            $form->handleRequest($request);
            $findStr = $form->getData()->getFind();
            $arr = explode(',', $findStr);
            $query = $manager->createNativeQuery('SELECT * FROM person WHERE age between ?1 AND ?2', $mapping)
                ->setParameters([1 => $arr[0], 2 => $arr[1]]);
            $result = $query->getResult();
        } else {
            $query = $manager->createNativeQuery('SELECT * FROM person', $mapping);
            $result = $query->getResult();
        }
        return $this->render('hello/find.html.twig', [
           'title' => 'Hello',
           'form' => $form->createView(),
            'data' => $result,
        ]);
    }


    /**
     * @Route("/create", name="create")
     * @param Request $request
     * @param ValidatorInterface $validator
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function create(Request $request ,ValidatorInterface $validator)
    {
        $form = $this->createFormBuilder()
            ->add('name', TextType::class,
                [
                    'required' => true,
                    'constraints' => [
                        new Assert\Length([
                            'min' => 3,
                            'max' => 10,
                            'minMessage' => '3文字以上必要です。',
                            'maxMessage' => '10文字以内にしてください。'
                        ])
                    ]
                ]
            )
            ->add('save', SubmitType::class, ['label' => 'Click'])
            ->getForm();
        if ($request->getMethod() === 'POST') {
            $form->handleRequest($request);
            if ($form->isValid()) {
                $msg = 'Hello, '. $form->get('name')->getData() . '!';
            } else {
                $msg = 'Error!';
            }
        } else {
            $msg = 'Send Form';
        }
        return $this->render('hello/create.html.twig' , [
            'title' => 'Hello',
            'message' => $msg,
            'form' => $form->createView()
        ]);

    }

    /**
     * @Route("/update/{id}", name="update")
     * @param Request $request
     * @param Person $person
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function update(Request $request, Person $person)
    {
        $form = $this->createFormBuilder($person)
            ->add('name', TextType::class)
            ->add('name', TextType::class)
            ->add('mail', TextType::class)
            ->add('age', IntegerType::class)
            ->add('save', SubmitType::class, ['label' => 'Click'])
            ->getForm();

        if ($request->getMethod() === 'POST') {
            $form->handleRequest($request);
            $person = $form->getData();
            $manager = $this->getDoctrine()->getManager();
            $manager->flush();
            return $this->redirect('/hello');
        } else {
            return $this->render('/hello/create.html.twig', [
               'title' => 'Hello',
               'message' => 'Update Entity id=' . $person->getId(),
               'form' => $form->createView(),
            ]);
        }
    }


    /**
     * @Route("/delete/{id}", name="delete")
     * @param Request $request
     * @param Person $person
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function delete(Request $request, Person $person)
    {
        $form = $this->createFormBuilder($person)
            ->add('name', TextType::class)
            ->add('mail', TextType::class)
            ->add('age', IntegerType::class)
            ->add('save', SubmitType::class, ['label' => 'Click'])
            ->getForm();

        if ($request->getMethod() === 'POST') {
            $form->handleRequest($request);
            $person = $form->getData();
            $manager = $this->getDoctrine()->getManager();
            $manager->remove($person);
            $manager->flush();
            return $this->redirect('/hello');
        } else {
            return $this->render('/hello/create.html.twig', [
                'title' => 'Hello',
                'message' => 'Delete Entity id=' . $person->getId(),
                'form' => $form->createView()
            ]);
        }
    }
}

class FindForm
{
    private $find;

    public function getFind()
    {
        return $this->find;
    }

    public function setFind($find)
    {
        $this->find = $find;
    }
}

class HelloForm
{
    private $name;
    private $mail;

    public function getName()
    {
        return $this->name;
    }

    public function setName($name)
    {
        $this->name = $name;
    }

    public function getMail()
    {
        return $this->mail;
    }

    public  function setMail($mail)
    {
        $this->mail = $mail;
    }

    public function __toString()
    {
        return '*** ' .$this->name. '['. $this->mail . '] ***';
    }
}

templates/hello/autoescape.html.twig
{% autoescape 'html' %}
    {{ leader }}
{% endautoescape %}

templates/hello/create.html.twig
{%  extends 'base.html.twig' %}

{% block page %}{{ title }}{% endblock %}
{% block title %}{{ title }}{% endblock %}

{% block body %}
    <h2>{{ message }}</h2>
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
{% endblock %}

templates/hello/filter.html.twig
{{ leader | raw }}
{{ leader | escape }}
<br>
{{ title | upper }}
<br>
{{ upper | lower }}
<br>
{{ title | capitalize }}
<br>
{{ minus | abs }}
<br>
{{ now | date('Y/m/d') }}
<br>
{{ data | json_encode }}
<br>
{{ leader | length }}
<br>
{{ minus | number_format(minus) }}
<br>
{{ title | reverse }}
<br>
{{ num | round }}
<br>
{% for n in nums | sort %}
{{ n }}
{% endfor %}

<br>
{{ upper | trim }}
<br>
{{ url | url_encode }}

templates/hello/find.html.twig
{%  extends 'base.html.twig' %}

{% block page %}{{ title }}{% endblock %}
{% block title %}{{ title }}{% endblock %}

{% block body %}
    <h2>Find Entity</h2>
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
    <hr>
    {% if data != null %}
        <ul>
            {% for item in data %}
                <li>{{ item.name }}({{ item.age }})</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

templates/hello/form.html.twig
{% import 'macro.html.twig' as m %}

<table>
    {{ m.input('text', 'Name', 'noname') }}
    {{ m.input('number', 'Age', '0') }}
    {{ m.input('email', 'Mail', 'no@mail') }}
    {{ m.submit('Click') }}
</table>

templates/hello/hello.html.twig
{%  extends 'base.html.twig' %}

{% block page %}{{ title }}{% endblock %}
{% block title %}{{ title }}{% endblock %}

{% block body %}
    <h2>{{ message }}</h2>
    <table>
        <tr>
            <th>ID</th>
            <td>{{ user.id }}</td>
        </tr>
        <tr>
            <th>Name</th>
            <td>{{ user.username }}</td>
        </tr>
        <tr>
            <td>Mail</td>
            <td>{{ user.email }}</td>
        </tr>
        <tr>
            <th>Role</th>
            <td>{{ user.roles[0] }}</td>
        </tr>
    </table>
{% endblock %}

templates/hello/index.html.twig
{%  extends 'base.html.twig' %}

{% block page %}{{ title }}{% endblock %}
{% block title %}{{ title }}{% endblock %}

{% block body %}
    <p>※テーブルを用意します。</p>
    {% include '/hello/table.html.twig' with [data] %}
    {% include '/hello/autoescape.html.twig' with [leader] %}
    {% include '/hello/filter.html.twig' with [leader] %}

{% endblock %}

templates/hello/table.html.twig
<style>
    .gray td{
        background: #ddd !important;
    }
    .blue td{
        background: #dff !important;
    }

</style>
<table>
    <tr>
        <th>Name</th>
        <th>Age</th>
        <th>Mail</th>
    </tr>
    {% set flg = true %}
    {% for item in data %}
        <tr class="{% if flg %}gray{% else %}blue{% endif %}">
            <td>{{ item.name }}</td>
            <td>{{ item.age }}</td>
            <td>{{ item.mail }}</td>
        </tr>
        {% if flg %}
            {% set flg = false %}
        {% else %}
            {% set flg = true %}
        {% endif %}
    {% endfor %}
</table>